spring.datasource.url=postgresql://postgres:balo82350100@db.bfrtfjhhrgdbsvmewjdf.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=monmotdepasse
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml